### ISSUE TITLE
Insertions fail when key too long

### ISSUE THREAD

**Issue by obibring** [apex/logs-js#4]
Hey there, seeing this error quite frequently:

```
Clustering encountered a key Msg_0_CLOUD_QUERY_TABLE.message that is 2115 
bytes long, which is more than the maximum allowed length of 1024 bytes.
```

I have an example request that's failing, but it's long and contains some potentially sensitive information that I don't trust myself to remove so I can send it privately.

Thanks!

**Comment by obibring** [comment]
I just looked at the message length, it's 59 characters. Is that error expected for such a length? Is their a recommended max length?

**Comment by tj** [comment]
No problem! Appreciate your team giving it a try, let me know if there's anything you feel is missing, I have a pretty huge to-do list but that can always help me prioritise.

> I just looked at the message length, it's 59 characters. Is that error expected for such a length? Is their a recommended max length?

hmm that doesn't sound right, I can't imagine even 59 multi-byte characters taking up 1024 bytes. I definitely use more than that for my own logs, I try to keep most of mine as actionable messages like "user login", "error sending email" etc, but I have a lot of longer plain-text from Lambda as well

**Comment by tj** [comment]
Yep, if you give it the same name you'll have the same slug used for the ID and all the logs will just start going there again. Technically you'd maybe have 30s of downtime or so, I don't know that there's a way around that unless it's a _new_ ID and you re-deploy stuff to point there

**Comment by obibring** [comment]
That's ok, 30s is manageable. Thanks again.

**Comment by tj** [comment]
Just a quick update. I have it almost ready to go, doing some QA today and then there should be a release tomorrow morning!

**Comment by tj** [comment]
If you run `$ logs upgrade && logs instance update` to update to v0.9.21 you should see a "Storage mode" option when creating a project, and the new plain-text option will remove this 1024 byte restriction.

If you wanted to retain your old logs you could create a new project, and start sending logs to that one instead, or like we talked about you could quickly delete/re-create a project with the same name to avoid re-deploying your app(s).

Let me know if there are any issues!

**Comment by obibring** [comment]
Great, thanks, upgrading now. I'm assuming there won't be any data loss when viewing the re-created project if the ids are the same?
