### ISSUE TITLE
Cannot copy id to clipboard

### ISSUE THREAD

**Issue by paulinawrzeszcz** [apex/logs-js#6]
When I click on id and choose "Copy to clipboard" I get "undefined" copied instead of id value.

It does work for all the other fields. For id it shows "Copied to clipboard" toast but doesn't copy the value.

**Comment by tj** [comment]
Thanks for pointing that out, I can reproduce it as well. I'll see what's going on there

**Comment by obibring** [comment]
Any update on this? Obviously a minor issue but we copy/paste values for quick debugging and doing it manually adds a lot of overhead when there are lots of bugs :)

**Comment by tj** [comment]
should have a chance to get this and a few other small fixes out today! Sorry for the delay, been busy with some other junk

**Comment by tj** [comment]
it was a pretty quick fix 😄  https://github.com/apex/logs/releases/tag/v0.9.23
